name: Content Guard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Auto-cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check headline
        run: |
          grep -r "Verifiable.*Delivery.*Record" frontend/src/app/ || (echo "Headline missing" && exit 1)
      
      - name: Check banned words
        run: |
          # Only check for marketing phrases, not technical terms
          ! grep -rE "(\\bsecure|trusted by|professionals|clients|\\bprotect\\b)" frontend/src/app/ frontend/src/components/ || (echo "Banned words found" && exit 1)
      
      - name: Check schema fields
        run: |
          grep -q "record_id" frontend/src/lib/schema.ts &&
          grep -q "sha256" frontend/src/lib/schema.ts &&
          grep -q "issued_at" frontend/src/lib/schema.ts &&
          grep -q "signature" frontend/src/lib/schema.ts &&
          grep -q "approved_by" frontend/src/lib/schema.ts &&
          grep -q "acknowledged_at" frontend/src/lib/schema.ts &&
          grep -q 'status.*closed' frontend/src/lib/schema.ts || (echo "Schema fields incomplete" && exit 1)
      
      - name: Check button centering
        run: |
          grep -q "flex items-center justify-center" frontend/src/app/check/page.tsx || (echo "Check button not centered" && exit 1)
