name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if tests fail'
        required: false
        default: false
        type: boolean
      skip_approval:
        description: 'Skip manual approval (requires admin privileges)'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "10.18.1"
  PRODUCTION_URL: "https://verisplatform.com"

jobs:
  # Pre-deployment checks
  pre-deploy-checks:
    name: Pre-deployment Checks
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check deployment conditions
        id: check
        run: |
          # Check if this is a forced deployment
          if [ "${{ github.event.inputs.force_deploy }}" == "true" ]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "Forced deployment requested"
            exit 0
          fi

          # Check if main branch has recent commits
          COMMITS_SINCE_LAST_DEPLOY=$(git log --oneline --since="1 hour ago" | wc -l)
          if [ $COMMITS_SINCE_LAST_DEPLOY -gt 0 ]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "Recent commits found, proceeding with deployment"
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "No recent commits, skipping deployment"
          fi

  # Comprehensive quality gates
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    needs: pre-deploy-checks
    if: needs.pre-deploy-checks.outputs.should_deploy == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm --filter frontend run typecheck

      - name: Lint check
        run: pnpm --filter frontend run lint

      - name: Security audit
        run: pnpm audit --audit-level moderate

      - name: Unit tests
        run: pnpm --filter frontend run test:ci
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_STRIPE_MODE: live
          CRON_JOB_TOKEN: ${{ secrets.PROD_CRON_JOB_TOKEN }}
          STRIPE_SECRET_KEY: ${{ secrets.PROD_STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.PROD_STRIPE_WEBHOOK_SECRET }}
          SUPABASE_SERVICE_KEY: ${{ secrets.PROD_SUPABASE_SERVICE_KEY }}
          VERIS_SIGNING_PRIVATE_KEY: ${{ secrets.PROD_VERIS_SIGNING_PRIVATE_KEY }}
          VERIS_SIGNING_PUBLIC_KEY: ${{ secrets.PROD_VERIS_SIGNING_PUBLIC_KEY }}

      - name: Build application
        run: pnpm --filter frontend run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_STRIPE_MODE: live
          NEXT_PUBLIC_SITE_URL: ${{ env.PRODUCTION_URL }}
          CRON_JOB_TOKEN: ${{ secrets.PROD_CRON_JOB_TOKEN }}
          STRIPE_SECRET_KEY: ${{ secrets.PROD_STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.PROD_STRIPE_WEBHOOK_SECRET }}
          SUPABASE_SERVICE_KEY: ${{ secrets.PROD_SUPABASE_SERVICE_KEY }}
          VERIS_SIGNING_PRIVATE_KEY: ${{ secrets.PROD_VERIS_SIGNING_PRIVATE_KEY }}
          VERIS_SIGNING_PUBLIC_KEY: ${{ secrets.PROD_VERIS_SIGNING_PUBLIC_KEY }}

      - name: Build SDK
        run: pnpm --filter sdk-js run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build-artifacts
          path: |
            frontend/.next/
            packages/sdk-js/dist/
          retention-days: 30

  # Manual approval for production
  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: [pre-deploy-checks, quality-gates]
    if: needs.pre-deploy-checks.outputs.should_deploy == 'true' && github.event.inputs.skip_approval != 'true'
    environment: production
    steps:
      - name: Request approval
        run: |
          echo "Production deployment requires manual approval"
          echo "Please review the changes and approve the deployment in the GitHub Actions UI"

  # Deploy to production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [pre-deploy-checks, quality-gates, manual-approval]
    if: |
      needs.pre-deploy-checks.outputs.should_deploy == 'true' && 
      (needs.manual-approval.result == 'success' || github.event.inputs.skip_approval == 'true')
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-build-artifacts
          path: .

      - name: Build for production
        run: pnpm --filter frontend run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_STRIPE_MODE: live
          NEXT_PUBLIC_SITE_URL: ${{ env.PRODUCTION_URL }}
          CRON_JOB_TOKEN: ${{ secrets.PROD_CRON_JOB_TOKEN }}
          STRIPE_SECRET_KEY: ${{ secrets.PROD_STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.PROD_STRIPE_WEBHOOK_SECRET }}
          SUPABASE_SERVICE_KEY: ${{ secrets.PROD_SUPABASE_SERVICE_KEY }}
          VERIS_SIGNING_PRIVATE_KEY: ${{ secrets.PROD_VERIS_SIGNING_PRIVATE_KEY }}
          VERIS_SIGNING_PUBLIC_KEY: ${{ secrets.PROD_VERIS_SIGNING_PUBLIC_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          REGISTRY_S3_BUCKET: ${{ secrets.PROD_REGISTRY_S3_BUCKET }}
          ARWEAVE_WALLET: ${{ secrets.PROD_ARWEAVE_WALLET }}

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          vercel-args: '--prod=true'

      - name: Wait for deployment
        run: |
          echo "Waiting for production deployment to be ready..."
          sleep 60

      - name: Health check
        run: |
          echo "Performing health check on production deployment..."
          curl -f "${{ env.PRODUCTION_URL }}/api/health" || exit 1
          echo "Production deployment is healthy!"

      - name: Run smoke tests
        run: |
          echo "Running smoke tests against production..."
          # Basic smoke tests
          curl -f "${{ env.PRODUCTION_URL }}/api/health" || exit 1
          curl -f "${{ env.PRODUCTION_URL }}/api/slo" || exit 1
          curl -f "${{ env.PRODUCTION_URL }}/api/performance" || exit 1
          echo "Smoke tests passed!"

      - name: Create deployment tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "deploy-$(date +%Y%m%d-%H%M%S)" -m "Production deployment $(date)"
          git push origin "deploy-$(date +%Y%m%d-%H%M%S)"

  # Post-deployment validation
  post-deploy-validation:
    name: Post-deployment Validation
    runs-on: ubuntu-latest
    needs: [pre-deploy-checks, deploy-production]
    if: needs.pre-deploy-checks.outputs.should_deploy == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm --filter frontend exec playwright install --with-deps

      - name: Run production E2E tests
        run: pnpm --filter frontend exec playwright test --config=playwright.config.production.ts
        env:
          BASE_URL: ${{ env.PRODUCTION_URL }}
          CI: true

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: production-e2e-results
          path: frontend/test-results/
          retention-days: 30

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Production deployment successful!"
            echo "🌐 Production URL: ${{ env.PRODUCTION_URL }}"
          else
            echo "❌ Production deployment failed!"
            exit 1
          fi

  # Rollback job (manual trigger)
  rollback:
    name: Rollback Production
    runs-on: ubuntu-latest
    if: failure() && github.event_name == 'workflow_dispatch'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rollback to previous deployment
        run: |
          echo "Rollback functionality would be implemented here"
          echo "This could involve:"
          echo "1. Reverting to previous Vercel deployment"
          echo "2. Rolling back database migrations"
          echo "3. Notifying team of rollback"
          echo "4. Creating incident report"
