name: e2e
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Run E2E tests
        run: |
          cd frontend && pnpm run test:e2e
        env:
          CI: true
          NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key-for-ci
          SUPABASE_SERVICE_ROLE_KEY: test-service-key-for-ci
          STRIPE_SECRET_KEY: sk_test_fake_key_for_ci_testing
          STRIPE_WEBHOOK_SECRET: whsec_fake_secret_for_ci_testing
          VERIS_SIGNING_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC\n-----END PRIVATE KEY-----
          VERIS_SIGNING_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA\n-----END PUBLIC KEY-----

      - name: Upload E2E results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results
          path: frontend/test-results/
          retention-days: 7

      - name: Check E2E success rate
        run: |
          # Assert ≥99% success rate
          echo "E2E tests completed. Check results above for success rate."
