name: Release Gate
on:
  push:
    branches: [main]

# Auto-cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Check last 3 runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the last 5 runs to account for cancelled runs due to concurrency
          RUNS=$(gh run list --workflow=e2e.yml --limit=5 --json conclusion --jq '.[].conclusion')
          
          # Count non-cancelled results
          NON_CANCELLED=$(echo "$RUNS" | grep -v "cancelled" || true)
          
          if [ -z "$NON_CANCELLED" ]; then
            echo "No completed runs found yet"
            echo "Gate passed (waiting for first run)"
            exit 0
          fi
          
          # Check if any non-cancelled runs failed
          NON_SUCCESS=$(echo "$NON_CANCELLED" | grep -v "success" || true)
          
          if [ -n "$NON_SUCCESS" ]; then
            echo "Not all recent runs passed"
            echo "$NON_SUCCESS"
            exit 1
          else
            echo "Gate passed"
          fi
