name: web_quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build application
        run: cd frontend && pnpm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key-for-ci
          SUPABASE_SERVICE_ROLE_KEY: test-service-key-for-ci
          STRIPE_SECRET_KEY: sk_test_fake_key_for_ci_testing
          STRIPE_WEBHOOK_SECRET: whsec_fake_secret_for_ci_testing
          VERIS_SIGNING_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC\n-----END PRIVATE KEY-----
          VERIS_SIGNING_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA\n-----END PUBLIC KEY-----

      - name: Start preview server
        run: cd frontend && pnpm start &
        env:
          NODE_ENV: production
          NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key-for-ci
          SUPABASE_SERVICE_ROLE_KEY: test-service-key-for-ci
          STRIPE_SECRET_KEY: sk_test_fake_key_for_ci_testing
          STRIPE_WEBHOOK_SECRET: whsec_fake_secret_for_ci_testing
          VERIS_SIGNING_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC\n-----END PRIVATE KEY-----
          VERIS_SIGNING_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA\n-----END PUBLIC KEY-----

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run a11y tests
        run: cd frontend && pnpm run a11y
        continue-on-error: true

      - name: Run Lighthouse
        run: cd frontend && pnpm run lighthouse
        continue-on-error: true

      - name: Check Web Vitals
        run: |
          echo "Web Vitals budgets:"
          echo "- LCP ≤ 1.8s"
          echo "- CLS ≤ 0.1"
          echo "- INP ≤ 200ms"
          echo "Review Lighthouse output above for compliance"
